# See the r-travis repo and its wiki 
#     https://github.com/eddelbuettel/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_r Rcpp
  - ./run.sh install_aptget r-cran-runit r-cran-knitr r-cran-rmarkdown

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
