// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_vector
std::vector< double > test_vector(std::vector< int > v, std::vector< double > v2);
RcppExport SEXP RcppHoney_test_vector(SEXP vSEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    Rcpp::traits::input_parameter< std::vector< double > >::type v2(v2SEXP);
    __result = Rcpp::wrap(test_vector(v, v2));
    return __result;
END_RCPP
}
