// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_hook
void test_hook();
RcppExport SEXP RcppHoney_test_hook() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    test_hook();
    return R_NilValue;
END_RCPP
}
// test_binary_operators
Rcpp::NumericVector test_binary_operators(std::vector< int > v, std::vector< double > v2, Rcpp::IntegerVector v3, Rcpp::NumericVector v4);
RcppExport SEXP RcppHoney_test_binary_operators(SEXP vSEXP, SEXP v2SEXP, SEXP v3SEXP, SEXP v4SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    Rcpp::traits::input_parameter< std::vector< double > >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type v3(v3SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v4(v4SEXP);
    __result = Rcpp::wrap(test_binary_operators(v, v2, v3, v4));
    return __result;
END_RCPP
}
// test_unary_operators
Rcpp::NumericVector test_unary_operators(std::vector< int > v);
RcppExport SEXP RcppHoney_test_unary_operators(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    __result = Rcpp::wrap(test_unary_operators(v));
    return __result;
END_RCPP
}
// test_unary_functions
Rcpp::NumericVector test_unary_functions(std::vector< int > v);
RcppExport SEXP RcppHoney_test_unary_functions(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    __result = Rcpp::wrap(test_unary_functions(v));
    return __result;
END_RCPP
}
// test_diff_function
Rcpp::IntegerVector test_diff_function(std::vector< int > v);
RcppExport SEXP RcppHoney_test_diff_function(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    __result = Rcpp::wrap(test_diff_function(v));
    return __result;
END_RCPP
}
// test_sugar_diff_function
Rcpp::IntegerVector test_sugar_diff_function(Rcpp::IntegerVector v);
RcppExport SEXP RcppHoney_test_sugar_diff_function(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type v(vSEXP);
    __result = Rcpp::wrap(test_sugar_diff_function(v));
    return __result;
END_RCPP
}
// test_naive_diff_function
Rcpp::IntegerVector test_naive_diff_function(std::vector< int > v);
RcppExport SEXP RcppHoney_test_naive_diff_function(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type v(vSEXP);
    __result = Rcpp::wrap(test_naive_diff_function(v));
    return __result;
END_RCPP
}
// test_diff_function2
Rcpp::IntegerVector test_diff_function2();
RcppExport SEXP RcppHoney_test_diff_function2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_diff_function2());
    return __result;
END_RCPP
}
// test_sugar_diff_function2
Rcpp::IntegerVector test_sugar_diff_function2();
RcppExport SEXP RcppHoney_test_sugar_diff_function2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_sugar_diff_function2());
    return __result;
END_RCPP
}
// test_naive_diff_function2
Rcpp::IntegerVector test_naive_diff_function2();
RcppExport SEXP RcppHoney_test_naive_diff_function2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_naive_diff_function2());
    return __result;
END_RCPP
}
