# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

example_manually_hooked <- function() {
    .Call('RcppHoney_example_manually_hooked', PACKAGE = 'RcppHoney')
}

