# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_vector <- function(v, v2) {
    .Call('RcppHoney_test_vector', PACKAGE = 'RcppHoney', v, v2)
}

