# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

example_manually_hooked <- function() {
    .Call('RcppHoney_example_manually_hooked', PACKAGE = 'RcppHoney')
}

test_hooked_plus_scalar <- function(v1, s) {
    .Call('RcppHoney_test_hooked_plus_scalar', PACKAGE = 'RcppHoney', v1, s)
}

test_scalar_plus_hooked <- function(s, v1) {
    .Call('RcppHoney_test_scalar_plus_hooked', PACKAGE = 'RcppHoney', s, v1)
}

test_hooked_plus_hooked <- function(v1, v2) {
    .Call('RcppHoney_test_hooked_plus_hooked', PACKAGE = 'RcppHoney', v1, v2)
}

test_hooked_plus_other_hooked <- function(v1, v2) {
    .Call('RcppHoney_test_hooked_plus_other_hooked', PACKAGE = 'RcppHoney', v1, v2)
}

test_other_hooked_plus_hooked <- function(v1, v2) {
    .Call('RcppHoney_test_other_hooked_plus_hooked', PACKAGE = 'RcppHoney', v1, v2)
}

test_operand_plus_scalar <- function(v1, v2, s) {
    .Call('RcppHoney_test_operand_plus_scalar', PACKAGE = 'RcppHoney', v1, v2, s)
}

test_scalar_plus_operand <- function(s, v1, v2) {
    .Call('RcppHoney_test_scalar_plus_operand', PACKAGE = 'RcppHoney', s, v1, v2)
}

test_operand_plus_hooked <- function(v1, v2, v3) {
    .Call('RcppHoney_test_operand_plus_hooked', PACKAGE = 'RcppHoney', v1, v2, v3)
}

test_hooked_plus_operand <- function(v1, v2, v3) {
    .Call('RcppHoney_test_hooked_plus_operand', PACKAGE = 'RcppHoney', v1, v2, v3)
}

test_operand_plus_operand <- function(s, v1, v2) {
    .Call('RcppHoney_test_operand_plus_operand', PACKAGE = 'RcppHoney', s, v1, v2)
}

test_unary_operator_hooked <- function(v) {
    .Call('RcppHoney_test_unary_operator_hooked', PACKAGE = 'RcppHoney', v)
}

test_unary_operator_operand <- function(v) {
    .Call('RcppHoney_test_unary_operator_operand', PACKAGE = 'RcppHoney', v)
}

test_unary_function_hooked <- function(v) {
    .Call('RcppHoney_test_unary_function_hooked', PACKAGE = 'RcppHoney', v)
}

test_unary_function_operand <- function(v) {
    .Call('RcppHoney_test_unary_function_operand', PACKAGE = 'RcppHoney', v)
}

